export const BRAND = {
  name: "Serene Homes Membley",
  tagline: "Stay Smart. Stay Secure. Stay Serene.",
  alternativeTaglines: [
    "Your Premium Home Between Nairobi & Tatu City",
    "Modern Comfort Along Eastern Bypass",
    "Where Business, Travel & Comfort Meet",
  ],
  host: "Paul",
  phone: "+254 725 896947",
  altPhone: "0114627575",
  location: {
    address: "Devivi Apartment, 2nd Floor",
    street: "Eastern Bypass, Membley Estate",
    city: "Ruiru, Kiambu County, Kenya",
  },
  colors: {
    primary: "#0F4C5C",
    secondary: "#2C7A7B",
    accent: "#D4AF37",
    background: "#F8F9FA",
    darkText: "#1F2937",
    mutedText: "#6B7280",
    success: "#16A34A",
  },
  advantages: [
    "Self Check-In",
    "24/7 Soldier-Manned Security",
    "Free Secure Parking",
    "Lift Access",
    "High-Speed WiFi",
    "Dedicated Workspace",
    "Smart TV Entertainment",
    "Fully Equipped Kitchen",
    "Modern Executive Interiors",
    "Quiet Environment",
    "Pet Friendly",
  ],
  nearby: [
    { name: "Magunas Supermarket", distance: "Walking distance" },
    { name: "Kamakis Entertainment District", distance: "5 mins" },
    { name: "Spur Mall", distance: "10 mins" },
    { name: "JKIA Airport", distance: "25 mins" },
    { name: "Nairobi CBD", distance: "30 mins" },
    { name: "Tatu City", distance: "10 mins" },
    { name: "Kenyatta University", distance: "10 mins" },
    { name: "JKUAT", distance: "15 mins" },
  ],
};
